using System.Collections.ObjectModel;
using System.Text;
using AKHENS_TRADER.Models;

namespace AKHENS_TRADER.Services
{
    /// <summary>
    /// Service responsible for generating MQL5 Expert Advisor code
    /// </summary>
    public class CodeGenerationService
    {
        /// <summary>
        /// Generates complete MQL5 Expert Advisor code based on strategy and prop firm settings
        /// </summary>
        /// <param name="strategy">The trading strategy configuration</param>
        /// <param name="preset">Prop firm preset settings</param>
        /// <returns>Complete MQL5 source code</returns>
        public string GenerateMQL5Code(Strategy strategy, PropFirmPreset preset)
        {
            var sb = new StringBuilder();

            // Header and properties
            GenerateHeader(sb, strategy);

            // Input parameters
            GenerateInputParameters(sb, strategy, preset);

            // Global variables
            GenerateGlobalVariables(sb);

            // OnInit function
            GenerateOnInit(sb, preset);

            // OnDeinit function
            GenerateOnDeinit(sb);

            // OnTick function
            GenerateOnTick(sb, strategy, preset);

            // Helper functions
            GenerateHelperFunctions(sb, strategy, preset);

            return sb.ToString();
        }

        #region Code Generation Methods

        /// <summary>
        /// Generate file header and properties
        /// </summary>
        private static void GenerateHeader(StringBuilder sb, Strategy strategy)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine($"//|                                     {strategy.Name,-20}|");
            sb.AppendLine("//|                        Generated by Prop Strategy Builder        |");
            sb.AppendLine($"//|                        {DateTime.Now:yyyy.MM.dd HH:mm}                        |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("#property copyright \"Generated by Prop Strategy Builder\"");
            sb.AppendLine("#property link      \"https://github.com/yourusername\"");
            sb.AppendLine("#property version   \"1.00\"");
            sb.AppendLine("#property strict");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate input parameters section
        /// </summary>
        private void GenerateInputParameters(StringBuilder sb, Strategy strategy, PropFirmPreset preset)
        {
            sb.AppendLine("//--- Input Parameters");
            sb.AppendLine("input group \"=== Risk Management ===\"");
            sb.AppendLine($"input double RiskPercent = {strategy.RiskSettings.RiskPercentPerTrade};              // Risk per trade (% of balance)");
            sb.AppendLine($"input int    StopLossPips = {strategy.RiskSettings.StopLossPips};              // Stop Loss (pips)");
            sb.AppendLine($"input int    TakeProfitPips = {strategy.RiskSettings.TakeProfitPips};           // Take Profit (pips)");
            sb.AppendLine($"input bool   UseTrailingStop = {(strategy.RiskSettings.UseTrailingStop ? "true" : "false")};        // Enable trailing stop");
            
            if (strategy.RiskSettings.UseTrailingStop)
            {
                sb.AppendLine($"input int    TrailingStopPips = {strategy.RiskSettings.TrailingStopPips};          // Trailing stop distance (pips)");
            }
            
            sb.AppendLine();
            sb.AppendLine("input group \"=== Prop Firm Settings ===\"");
            sb.AppendLine($"input double MaxDailyDrawdown = {preset.DailyDrawdownPercent};         // Max Daily Drawdown (%)");
            sb.AppendLine($"input double MaxTotalDrawdown = {preset.MaxDrawdownPercent};        // Max Total Drawdown (%)");
            sb.AppendLine($"input int    MaxOpenTrades = {preset.MaxOpenTrades};              // Maximum concurrent trades");
            sb.AppendLine($"input int    MagicNumber = {preset.MagicNumber};           // EA Magic Number");
            sb.AppendLine();
            
            // Strategy-specific parameters
            if (strategy.EntryConditions.Count > 0)
            {
                sb.AppendLine("input group \"=== Strategy Parameters ===\"");
                GenerateStrategyParameters(sb, strategy);
                sb.AppendLine();
            }
        }

        /// <summary>
        /// Generate strategy-specific parameters based on indicators used
        /// </summary>
        private static void GenerateStrategyParameters(StringBuilder sb, Strategy strategy)
        {
            HashSet<IndicatorType> usedIndicators = [];
            
            foreach (var condition in strategy.EntryConditions.Concat(strategy.ExitConditions))
            {
                if (!usedIndicators.Contains(condition.Type))
                {
                    usedIndicators.Add(condition.Type);
                    
                    switch (condition.Type)
                    {
                        case IndicatorType.MA:
                        case IndicatorType.SMA:
                        case IndicatorType.EMA:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.RSI:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.MACD:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.BollingerBands:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.Stochastic:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.CCI:
                            // Parameters already embedded in condition
                            break;
                        case IndicatorType.ATR:
                            // Parameters already embedded in condition
                            break;
                    }
                }
            }
            
            // If no conditions specified, add default parameters
            if (usedIndicators.Count == 0)
            {
                sb.AppendLine("// No custom indicators configured");
            }
        }

        /// <summary>
        /// Generate global variables
        /// </summary>
        private static void GenerateGlobalVariables(StringBuilder sb)
        {
            sb.AppendLine("//--- Global Variables");
            sb.AppendLine("double g_initialBalance;");
            sb.AppendLine("double g_dailyStartBalance;");
            sb.AppendLine("datetime g_lastDayCheck;");
            sb.AppendLine("int g_openTrades = 0;");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate OnInit function
        /// </summary>
        private static void GenerateOnInit(StringBuilder sb, PropFirmPreset preset)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Expert initialization function                                   |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("int OnInit()");
            sb.AppendLine("{");
            sb.AppendLine("    // Store initial balance for drawdown calculation");
            sb.AppendLine("    g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);");
            sb.AppendLine("    g_dailyStartBalance = g_initialBalance;");
            sb.AppendLine("    g_lastDayCheck = TimeCurrent();");
            sb.AppendLine("    ");
            sb.AppendLine("    Print(\"================================\");");
            sb.AppendLine($"    Print(\"{preset.FirmName} Strategy EA Initialized\");");
            sb.AppendLine("    Print(\"Initial Balance: \", g_initialBalance);");
            sb.AppendLine($"    Print(\"Max Daily DD: {preset.DailyDrawdownPercent}%\");");
            sb.AppendLine($"    Print(\"Max Total DD: {preset.MaxDrawdownPercent}%\");");
            sb.AppendLine("    Print(\"================================\");");
            sb.AppendLine("    ");
            sb.AppendLine("    return(INIT_SUCCEEDED);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate OnDeinit function
        /// </summary>
        private static void GenerateOnDeinit(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Expert deinitialization function                                 |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void OnDeinit(const int reason)");
            sb.AppendLine("{");
            sb.AppendLine("    Print(\"EA stopped. Reason: \", reason);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate OnTick function with strategy logic
        /// </summary>
        private static void GenerateOnTick(StringBuilder sb, Strategy strategy, PropFirmPreset preset)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Expert tick function                                             |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void OnTick()");
            sb.AppendLine("{");
            sb.AppendLine("    // Update daily balance check (reset at midnight)");
            sb.AppendLine("    CheckDailyReset();");
            sb.AppendLine("    ");
            
            if (preset.EnableDrawdownMonitoring)
            {
                sb.AppendLine("    // Check drawdown limits before any action");
                sb.AppendLine("    if (!CheckDrawdownLimits())");
                sb.AppendLine("    {");
                sb.AppendLine("        Comment(\"DRAWDOWN LIMIT REACHED - Trading stopped!\");");
                sb.AppendLine("        CloseAllPositions();");
                sb.AppendLine("        return;");
                sb.AppendLine("    }");
                sb.AppendLine("    ");
            }
            
            sb.AppendLine("    // Update open trades count");
            sb.AppendLine("    g_openTrades = CountOpenPositions();");
            sb.AppendLine("    ");
            sb.AppendLine("    // Check if max trades reached");
            sb.AppendLine($"    if (g_openTrades >= MaxOpenTrades)");
            sb.AppendLine("    {");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine("    ");
            sb.AppendLine("    // Check entry signals");
            sb.AppendLine("    CheckEntrySignals();");
            sb.AppendLine("    ");
            sb.AppendLine("    // Check exit signals");
            sb.AppendLine("    CheckExitSignals();");
            sb.AppendLine("    ");
            
            if (strategy.RiskSettings.UseTrailingStop)
            {
                sb.AppendLine("    // Update trailing stops");
                sb.AppendLine("    UpdateTrailingStops();");
                sb.AppendLine("    ");
            }
            
            sb.AppendLine("    // Update chart comment");
            sb.AppendLine("    UpdateComment();");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate all helper functions
        /// </summary>
        private void GenerateHelperFunctions(StringBuilder sb, Strategy strategy, PropFirmPreset preset)
        {
            GenerateCheckEntrySignals(sb, strategy);
            GenerateCheckExitSignals(sb, strategy);
            GenerateOpenOrders(sb, preset);
            GenerateCalculateLotSize(sb);
            GenerateDrawdownFunctions(sb);
            GeneratePositionManagement(sb);
            
            if (strategy.RiskSettings.UseTrailingStop)
            {
                GenerateTrailingStop(sb);
            }
            
            GenerateUpdateComment(sb);
        }

        /// <summary>
        /// Generate CheckEntrySignals function
        /// </summary>
        private void GenerateCheckEntrySignals(StringBuilder sb, Strategy strategy)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Check entry signals                                              |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void CheckEntrySignals()");
            sb.AppendLine("{");
            
            if (strategy.EntryConditions.Count > 0)
            {
                sb.AppendLine("    // Entry conditions based on your strategy");
                GenerateConditionLogic(sb, strategy.EntryConditions, "entry");
            }
            else
            {
                sb.AppendLine("    // Example: Simple MA + RSI strategy");
                sb.AppendLine("    double ma = iMA(_Symbol, PERIOD_CURRENT, MA_Period, 0, MODE_SMA, PRICE_CLOSE);");
                sb.AppendLine("    double rsi = iRSI(_Symbol, PERIOD_CURRENT, RSI_Period, PRICE_CLOSE);");
                sb.AppendLine("    double close = iClose(_Symbol, PERIOD_CURRENT, 0);");
                sb.AppendLine("    ");
                sb.AppendLine("    // Buy signal: Price above MA and RSI oversold");
                sb.AppendLine("    if (close > ma && rsi < 30.0)");
                sb.AppendLine("    {");
                sb.AppendLine("        OpenBuyOrder();");
                sb.AppendLine("    }");
                sb.AppendLine("    ");
                sb.AppendLine("    // Sell signal: Price below MA and RSI overbought");
                sb.AppendLine("    if (close < ma && rsi > 70.0)");
                sb.AppendLine("    {");
                sb.AppendLine("        OpenSellOrder();");
                sb.AppendLine("    }");
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate CheckExitSignals function
        /// </summary>
        private void GenerateCheckExitSignals(StringBuilder sb, Strategy strategy)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Check exit signals                                               |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void CheckExitSignals()");
            sb.AppendLine("{");
            
            if (strategy.ExitConditions.Count > 0)
            {
                sb.AppendLine("    // Exit conditions based on your strategy");
                GenerateConditionLogic(sb, strategy.ExitConditions, "exit");
            }
            else
            {
                sb.AppendLine("    // Exit logic will be based on SL/TP set at order entry");
                sb.AppendLine("    // Add custom exit conditions here if needed");
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate condition evaluation logic
        /// </summary>
        private void GenerateConditionLogic(StringBuilder sb, ObservableCollection<IndicatorCondition> conditions, string type)
        {
            if (conditions.Count == 0)
            {
                sb.AppendLine("    // No conditions defined");
                return;
            }

            sb.AppendLine("    // Evaluate conditions");
            
            for (int i = 0; i < conditions.Count; i++)
            {
                var condition = conditions[i];
                var condVar = $"cond{i + 1}";
                var timeframe = condition.Timeframe;
                
                // Generate indicator value
                switch (condition.Type)
                {
                    case IndicatorType.RSI:
                        sb.AppendLine($"    double {condVar}_value = iRSI(_Symbol, {timeframe}, {condition.Period}, PRICE_CLOSE);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_value {GetOperatorSymbol(condition.Operator)} {condition.Level};");
                        break;
                        
                    case IndicatorType.MA:
                    case IndicatorType.SMA:
                    case IndicatorType.EMA:
                        var maMethod = condition.Type == IndicatorType.EMA ? "MODE_EMA" : "MODE_SMA";
                        sb.AppendLine($"    double {condVar}_ma = iMA(_Symbol, {timeframe}, {condition.Period}, 0, {maMethod}, PRICE_CLOSE);");
                        sb.AppendLine($"    double {condVar}_price = iClose(_Symbol, {timeframe}, 0);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_price {GetOperatorSymbol(condition.Operator)} {condVar}_ma;");
                        break;
                        
                    case IndicatorType.MACD:
                        sb.AppendLine($"    double {condVar}_macd[], {condVar}_signal[];");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_macd, true);");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_signal, true);");
                        sb.AppendLine($"    int {condVar}_handle = iMACD(_Symbol, {timeframe}, {condition.FastEMA}, {condition.SlowEMA}, {condition.SignalSMA}, PRICE_CLOSE);");
                        sb.AppendLine($"    CopyBuffer({condVar}_handle, 0, 0, 2, {condVar}_macd);");
                        sb.AppendLine($"    CopyBuffer({condVar}_handle, 1, 0, 2, {condVar}_signal);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_macd[0] {GetOperatorSymbol(condition.Operator)} {condVar}_signal[0];");
                        break;
                        
                    case IndicatorType.BollingerBands:
                        sb.AppendLine($"    double {condVar}_upper[], {condVar}_lower[];");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_upper, true);");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_lower, true);");
                        sb.AppendLine($"    int {condVar}_handle = iBands(_Symbol, {timeframe}, {condition.Period}, 0, {condition.Deviation}, PRICE_CLOSE);");
                        sb.AppendLine($"    CopyBuffer({condVar}_handle, 1, 0, 1, {condVar}_upper);");
                        sb.AppendLine($"    CopyBuffer({condVar}_handle, 2, 0, 1, {condVar}_lower);");
                        sb.AppendLine($"    double {condVar}_price = iClose(_Symbol, {timeframe}, 0);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_price {GetOperatorSymbol(condition.Operator)} {condVar}_lower[0];");
                        break;
                        
                        
                    case IndicatorType.Stochastic:
                        sb.AppendLine($"    double {condVar}_main[], {condVar}_signal[];");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_main, true);");
                        sb.AppendLine($"    ArraySetAsSeries({condVar}_signal, true);");
                        sb.AppendLine($"    int {condVar}_handle = iStochastic(_Symbol, {timeframe}, {condition.KPeriod}, {condition.DPeriod}, {condition.Slowing}, MODE_SMA, STO_LOWHIGH);");
                        sb.AppendLine($"    CopyBuffer({condVar}_handle, 0, 0, 1, {condVar}_main);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_main[0] {GetOperatorSymbol(condition.Operator)} {condition.Level};");
                        break;
                        
                    case IndicatorType.CCI:
                        sb.AppendLine($"    double {condVar}_value = iCCI(_Symbol, {timeframe}, {condition.Period}, PRICE_TYPICAL);");
                        sb.AppendLine($"    bool {condVar} = {condVar}_value {GetOperatorSymbol(condition.Operator)} {condition.Level};");
                        break;
                        
                    case IndicatorType.ATR:
                        sb.AppendLine($"    double {condVar}_value = iATR(_Symbol, {timeframe}, {condition.Period});");
                        sb.AppendLine($"    bool {condVar} = {condVar}_value {GetOperatorSymbol(condition.Operator)} {condition.Level};");
                        break;
                }

                
                sb.AppendLine();
            }
            
            // Build the combined condition
            sb.Append("    if (");
            for (int i = 0; i < conditions.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(conditions[i].IsAnd ? " && " : " || ");
                }
                sb.Append($"cond{i + 1}");
            }
            sb.AppendLine(")");
            sb.AppendLine("    {");
            if (type == "entry")
            {
                sb.AppendLine("        // Entry signal detected - open trade");
                sb.AppendLine("        OpenBuyOrder();  // Or OpenSellOrder() based on your strategy");
            }
            else
            {
                sb.AppendLine("        // Exit signal detected - close positions");
                sb.AppendLine("        CloseAllPositions();");
            }
            sb.AppendLine("    }");
        }

        /// <summary>
        /// Get MQL5 comparison operator symbol
        /// </summary>
        private static string GetOperatorSymbol(ComparisonOperator op)
        {
            return op switch
            {
                ComparisonOperator.GreaterThan => ">",
                ComparisonOperator.LessThan => "<",
                ComparisonOperator.Equal => "==",
                ComparisonOperator.NotEqual => "!=",
                ComparisonOperator.CrossAbove => ">",
                ComparisonOperator.CrossBelow => "<",
                _ => ">"
            };
        }

        /// <summary>
        /// Generate order opening functions
        /// </summary>
        private static void GenerateOpenOrders(StringBuilder sb, PropFirmPreset preset)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Open Buy Order                                                   |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void OpenBuyOrder()");
            sb.AppendLine("{");
            sb.AppendLine("    double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);");
            sb.AppendLine("    double sl = price - StopLossPips * _Point * 10;");
            sb.AppendLine("    double tp = price + TakeProfitPips * _Point * 10;");
            sb.AppendLine("    ");
            sb.AppendLine("    double lotSize = CalculateLotSize(StopLossPips);");
            sb.AppendLine("    ");
            sb.AppendLine("    MqlTradeRequest request = {};");
            sb.AppendLine("    MqlTradeResult result = {};");
            sb.AppendLine("    ");
            sb.AppendLine("    request.action = TRADE_ACTION_DEAL;");
            sb.AppendLine("    request.symbol = _Symbol;");
            sb.AppendLine("    request.volume = lotSize;");
            sb.AppendLine("    request.type = ORDER_TYPE_BUY;");
            sb.AppendLine("    request.price = price;");
            
            if (preset.EnforceVisibleSLTP)
            {
                sb.AppendLine("    request.sl = sl;        // Visible SL (required by prop firm)");
                sb.AppendLine("    request.tp = tp;        // Visible TP (required by prop firm)");
            }
            
            sb.AppendLine("    request.deviation = 10;");
            sb.AppendLine("    request.magic = MagicNumber;");
            sb.AppendLine("    request.comment = \"Buy Order\";");
            sb.AppendLine("    ");
            sb.AppendLine("    if (OrderSend(request, result))");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"Buy order opened: \", result.order, \" at \", price);");
            sb.AppendLine("    }");
            sb.AppendLine("    else");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"Buy order failed: \", GetLastError());");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            
            // Sell order
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Open Sell Order                                                  |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void OpenSellOrder()");
            sb.AppendLine("{");
            sb.AppendLine("    double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);");
            sb.AppendLine("    double sl = price + StopLossPips * _Point * 10;");
            sb.AppendLine("    double tp = price - TakeProfitPips * _Point * 10;");
            sb.AppendLine("    ");
            sb.AppendLine("    double lotSize = CalculateLotSize(StopLossPips);");
            sb.AppendLine("    ");
            sb.AppendLine("    MqlTradeRequest request = {};");
            sb.AppendLine("    MqlTradeResult result = {};");
            sb.AppendLine("    ");
            sb.AppendLine("    request.action = TRADE_ACTION_DEAL;");
            sb.AppendLine("    request.symbol = _Symbol;");
            sb.AppendLine("    request.volume = lotSize;");
            sb.AppendLine("    request.type = ORDER_TYPE_SELL;");
            sb.AppendLine("    request.price = price;");
            
            if (preset.EnforceVisibleSLTP)
            {
                sb.AppendLine("    request.sl = sl;        // Visible SL (required by prop firm)");
                sb.AppendLine("    request.tp = tp;        // Visible TP (required by prop firm)");
            }
            
            sb.AppendLine("    request.deviation = 10;");
            sb.AppendLine("    request.magic = MagicNumber;");
            sb.AppendLine("    request.comment = \"Sell Order\";");
            sb.AppendLine("    ");
            sb.AppendLine("    if (OrderSend(request, result))");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"Sell order opened: \", result.order, \" at \", price);");
            sb.AppendLine("    }");
            sb.AppendLine("    else");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"Sell order failed: \", GetLastError());");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate lot size calculation function
        /// </summary>
        private static void GenerateCalculateLotSize(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Calculate lot size based on risk percentage                      |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("double CalculateLotSize(int stopLossPips)");
            sb.AppendLine("{");
            sb.AppendLine("    double balance = AccountInfoDouble(ACCOUNT_BALANCE);");
            sb.AppendLine("    double riskAmount = balance * (RiskPercent / 100.0);");
            sb.AppendLine("    ");
            sb.AppendLine("    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);");
            sb.AppendLine("    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);");
            sb.AppendLine("    double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);");
            sb.AppendLine("    ");
            sb.AppendLine("    double stopLossAmount = stopLossPips * point * 10 / tickSize * tickValue;");
            sb.AppendLine("    double lotSize = riskAmount / stopLossAmount;");
            sb.AppendLine("    ");
            sb.AppendLine("    // Round to allowed lot step");
            sb.AppendLine("    double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);");
            sb.AppendLine("    lotSize = MathFloor(lotSize / lotStep) * lotStep;");
            sb.AppendLine("    ");
            sb.AppendLine("    // Check min/max lot");
            sb.AppendLine("    double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);");
            sb.AppendLine("    double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);");
            sb.AppendLine("    ");
            sb.AppendLine("    lotSize = MathMax(minLot, MathMin(maxLot, lotSize));");
            sb.AppendLine("    ");
            sb.AppendLine("    return lotSize;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate drawdown monitoring functions
        /// </summary>
        private static void GenerateDrawdownFunctions(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Check drawdown limits (CRITICAL for prop firms)                 |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("bool CheckDrawdownLimits()");
            sb.AppendLine("{");
            sb.AppendLine("    double currentBalance = AccountInfoDouble(ACCOUNT_BALANCE);");
            sb.AppendLine("    double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);");
            sb.AppendLine("    ");
            sb.AppendLine("    // Calculate daily drawdown");
            sb.AppendLine("    double dailyDD = ((g_dailyStartBalance - currentEquity) / g_dailyStartBalance) * 100.0;");
            sb.AppendLine("    ");
            sb.AppendLine("    // Calculate total drawdown");
            sb.AppendLine("    double totalDD = ((g_initialBalance - currentEquity) / g_initialBalance) * 100.0;");
            sb.AppendLine("    ");
            sb.AppendLine("    if (dailyDD >= MaxDailyDrawdown)");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"ALERT: Daily drawdown limit reached! \", dailyDD, \"% / \", MaxDailyDrawdown, \"%\");");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine("    ");
            sb.AppendLine("    if (totalDD >= MaxTotalDrawdown)");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"ALERT: Total drawdown limit reached! \", totalDD, \"% / \", MaxTotalDrawdown, \"%\");");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine("    ");
            sb.AppendLine("    return true;");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Reset daily balance at midnight                                  |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void CheckDailyReset()");
            sb.AppendLine("{");
            sb.AppendLine("    datetime currentTime = TimeCurrent();");
            sb.AppendLine("    MqlDateTime timeStruct;");
            sb.AppendLine("    TimeToStruct(currentTime, timeStruct);");
            sb.AppendLine("    ");
            sb.AppendLine("    if (timeStruct.hour == 0 && timeStruct.min == 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (TimeCurrent() - g_lastDayCheck > 3600) // Avoid multiple resets");
            sb.AppendLine("        {");
            sb.AppendLine("            g_dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);");
            sb.AppendLine("            g_lastDayCheck = currentTime;");
            sb.AppendLine("            Print(\"Daily balance reset: \", g_dailyStartBalance);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate position management functions
        /// </summary>
        private static void GeneratePositionManagement(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Count open positions with our magic number                       |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("int CountOpenPositions()");
            sb.AppendLine("{");
            sb.AppendLine("    int count = 0;");
            sb.AppendLine("    for (int i = 0; i < PositionsTotal(); i++)");
            sb.AppendLine("    {");
            sb.AppendLine("        ulong ticket = PositionGetTicket(i);");
            sb.AppendLine("        if (PositionSelectByTicket(ticket))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (PositionGetInteger(POSITION_MAGIC) == MagicNumber)");
            sb.AppendLine("            {");
            sb.AppendLine("                count++;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    return count;");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Close a specific position                                        |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void ClosePosition(ulong ticket)");
            sb.AppendLine("{");
            sb.AppendLine("    MqlTradeRequest request = {};");
            sb.AppendLine("    MqlTradeResult result = {};");
            sb.AppendLine("    ");
            sb.AppendLine("    if (PositionSelectByTicket(ticket))");
            sb.AppendLine("    {");
            sb.AppendLine("        request.action = TRADE_ACTION_DEAL;");
            sb.AppendLine("        request.position = ticket;");
            sb.AppendLine("        request.symbol = PositionGetString(POSITION_SYMBOL);");
            sb.AppendLine("        request.volume = PositionGetDouble(POSITION_VOLUME);");
            sb.AppendLine("        request.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;");
            sb.AppendLine("        request.price = (request.type == ORDER_TYPE_SELL) ? SymbolInfoDouble(request.symbol, SYMBOL_BID) : SymbolInfoDouble(request.symbol, SYMBOL_ASK);");
            sb.AppendLine("        request.deviation = 10;");
            sb.AppendLine("        request.magic = MagicNumber;");
            sb.AppendLine("        ");
            sb.AppendLine("        if (OrderSend(request, result))");
            sb.AppendLine("        {");
            sb.AppendLine("            Print(\"Position closed: \", ticket);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Close all positions                                              |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void CloseAllPositions()");
            sb.AppendLine("{");
            sb.AppendLine("    for (int i = PositionsTotal() - 1; i >= 0; i--)");
            sb.AppendLine("    {");
            sb.AppendLine("        ulong ticket = PositionGetTicket(i);");
            sb.AppendLine("        if (PositionSelectByTicket(ticket))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (PositionGetInteger(POSITION_MAGIC) == MagicNumber)");
            sb.AppendLine("            {");
            sb.AppendLine("                ClosePosition(ticket);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate trailing stop function
        /// </summary>
        private static void GenerateTrailingStop(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Update trailing stops                                            |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void UpdateTrailingStops()");
            sb.AppendLine("{");
            sb.AppendLine("    for (int i = 0; i < PositionsTotal(); i++)");
            sb.AppendLine("    {");
            sb.AppendLine("        ulong ticket = PositionGetTicket(i);");
            sb.AppendLine("        if (PositionSelectByTicket(ticket))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (PositionGetInteger(POSITION_MAGIC) != MagicNumber)");
            sb.AppendLine("                continue;");
            sb.AppendLine("                ");
            sb.AppendLine("            double currentSL = PositionGetDouble(POSITION_SL);");
            sb.AppendLine("            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);");
            sb.AppendLine("            ENUM_POSITION_TYPE posType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);");
            sb.AppendLine("            ");
            sb.AppendLine("            double trailDistance = TrailingStopPips * _Point * 10;");
            sb.AppendLine("            ");
            sb.AppendLine("            if (posType == POSITION_TYPE_BUY)");
            sb.AppendLine("            {");
            sb.AppendLine("                double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);");
            sb.AppendLine("                double newSL = currentPrice - trailDistance;");
            sb.AppendLine("                ");
            sb.AppendLine("                if (newSL > currentSL && newSL > openPrice)");
            sb.AppendLine("                {");
            sb.AppendLine("                    ModifyPosition(ticket, newSL, PositionGetDouble(POSITION_TP));");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (posType == POSITION_TYPE_SELL)");
            sb.AppendLine("            {");
            sb.AppendLine("                double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);");
            sb.AppendLine("                double newSL = currentPrice + trailDistance;");
            sb.AppendLine("                ");
            sb.AppendLine("                if (newSL < currentSL && newSL < openPrice)");
            sb.AppendLine("                {");
            sb.AppendLine("                    ModifyPosition(ticket, newSL, PositionGetDouble(POSITION_TP));");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Modify position SL/TP                                            |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void ModifyPosition(ulong ticket, double sl, double tp)");
            sb.AppendLine("{");
            sb.AppendLine("    MqlTradeRequest request = {};");
            sb.AppendLine("    MqlTradeResult result = {};");
            sb.AppendLine("    ");
            sb.AppendLine("    request.action = TRADE_ACTION_SLTP;");
            sb.AppendLine("    request.position = ticket;");
            sb.AppendLine("    request.sl = sl;");
            sb.AppendLine("    request.tp = tp;");
            sb.AppendLine("    ");
            sb.AppendLine("    if (OrderSend(request, result))");
            sb.AppendLine("    {");
            sb.AppendLine("        Print(\"Position modified: \", ticket, \" new SL: \", sl);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Generate chart comment update function
        /// </summary>
        private static void GenerateUpdateComment(StringBuilder sb)
        {
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("//| Update chart comment                                             |");
            sb.AppendLine("//+------------------------------------------------------------------+");
            sb.AppendLine("void UpdateComment()");
            sb.AppendLine("{");
            sb.AppendLine("    double currentBalance = AccountInfoDouble(ACCOUNT_BALANCE);");
            sb.AppendLine("    double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);");
            sb.AppendLine("    double dailyDD = ((g_dailyStartBalance - currentEquity) / g_dailyStartBalance) * 100.0;");
            sb.AppendLine("    double totalDD = ((g_initialBalance - currentEquity) / g_initialBalance) * 100.0;");
            sb.AppendLine("    ");
            sb.AppendLine("    string comment = \"\\n\";");
            sb.AppendLine("    comment += \"===== PROP STRATEGY EA =====\\n\";");
            sb.AppendLine("    comment += \"Open Trades: \" + IntegerToString(g_openTrades) + \" / \" + IntegerToString(MaxOpenTrades) + \"\\n\";");
            sb.AppendLine("    comment += \"Balance: $\" + DoubleToString(currentBalance, 2) + \"\\n\";");
            sb.AppendLine("    comment += \"Equity: $\" + DoubleToString(currentEquity, 2) + \"\\n\";");
            sb.AppendLine("    comment += \"Daily DD: \" + DoubleToString(dailyDD, 2) + \"% / \" + DoubleToString(MaxDailyDrawdown, 2) + \"%\\n\";");
            sb.AppendLine("    comment += \"Total DD: \" + DoubleToString(totalDD, 2) + \"% / \" + DoubleToString(MaxTotalDrawdown, 2) + \"%\\n\";");
            sb.AppendLine("    comment += \"============================\\n\";");
            sb.AppendLine("    ");
            sb.AppendLine("    Comment(comment);");
            sb.AppendLine("}");
            sb.AppendLine("//+------------------------------------------------------------------+");
        }

        #endregion
    }
}
