//+------------------------------------------------------------------+
//|                                     PropStrategyEA.mq5           |
//|                        Generated by Prop Strategy Builder        |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Generated by Prop Strategy Builder"
#property link      "https://github.com/yourusername"
#property version   "1.00"
#property strict

//--- Input Parameters
input group "=== Risk Management ==="
input double RiskPercent = 1.0;              // Risk per trade (% of balance)
input int    StopLossPips = 50;              // Stop Loss (pips)
input int    TakeProfitPips = 100;           // Take Profit (pips)
input bool   UseTrailingStop = false;        // Enable trailing stop
input int    TrailingStopPips = 30;          // Trailing stop distance (pips)

input group "=== Prop Firm Settings ==="
input double MaxDailyDrawdown = 5.0;         // Max Daily Drawdown (%)
input double MaxTotalDrawdown = 10.0;        // Max Total Drawdown (%)
input int    MaxOpenTrades = 3;              // Maximum concurrent trades
input int    MagicNumber = 123456;           // EA Magic Number

input group "=== Trading Hours ==="
input bool   UseTimeFilter = false;          // Enable time filter
input int    StartHour = 8;                  // Start hour (0-23)
input int    EndHour = 18;                   // End hour (0-23)

input group "=== Strategy Parameters ==="
// {{STRATEGY_INPUTS}} - Will be replaced by actual strategy parameters
input int    MA_Period = 20;                 // Moving Average Period
input int    RSI_Period = 14;                // RSI Period
input double RSI_Overbought = 70.0;          // RSI Overbought Level
input double RSI_Oversold = 30.0;            // RSI Oversold Level

//--- Global Variables
double g_initialBalance;
double g_dailyStartBalance;
datetime g_lastDayCheck;
int g_openTrades = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    // Store initial balance for drawdown calculation
    g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
    g_dailyStartBalance = g_initialBalance;
    g_lastDayCheck = TimeCurrent();
    
    Print("================================");
    Print("Prop Strategy EA Initialized");
    Print("Initial Balance: ", g_initialBalance);
    Print("Max Daily DD: ", MaxDailyDrawdown, "%");
    Print("Max Total DD: ", MaxTotalDrawdown, "%");
    Print("Magic Number: ", MagicNumber);
    Print("================================");
    
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("EA stopped. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // Update daily balance check (reset at midnight)
    CheckDailyReset();
    
    // Check drawdown limits before any action
    if (!CheckDrawdownLimits())
    {
        Comment("DRAWDOWN LIMIT REACHED - Trading stopped!");
        CloseAllPositions();
        return;
    }
    
    // Check time filter
    if (UseTimeFilter && !IsWithinTradingHours())
    {
        return;
    }
    
    // Update open trades count
    g_openTrades = CountOpenPositions();
    
    // Check if max trades reached
    if (g_openTrades >= MaxOpenTrades)
    {
        return;
    }
    
    // {{ENTRY_LOGIC}} - Will be replaced by actual entry conditions
    CheckEntrySignals();
    
    // {{EXIT_LOGIC}} - Will be replaced by actual exit conditions
    CheckExitSignals();
    
    // Update trailing stops if enabled
    if (UseTrailingStop)
    {
        UpdateTrailingStops();
    }
    
    UpdateComment();
}

//+------------------------------------------------------------------+
//| Check entry signals                                              |
//+------------------------------------------------------------------+
void CheckEntrySignals()
{
    // {{ENTRY_CONDITIONS}}
    // This section will be populated based on user's strategy
    
    // Example: Simple MA + RSI strategy
    double ma = iMA(_Symbol, PERIOD_CURRENT, MA_Period, 0, MODE_SMA, PRICE_CLOSE);
    double rsi = iRSI(_Symbol, PERIOD_CURRENT, RSI_Period, PRICE_CLOSE);
    double close = iClose(_Symbol, PERIOD_CURRENT, 0);
    
    // Buy signal: Price above MA and RSI oversold
    if (close > ma && rsi < RSI_Oversold)
    {
        OpenBuyOrder();
    }
    
    // Sell signal: Price below MA and RSI overbought
    if (close < ma && rsi > RSI_Overbought)
    {
        OpenSellOrder();
    }
}

//+------------------------------------------------------------------+
//| Check exit signals                                               |
//+------------------------------------------------------------------+
void CheckExitSignals()
{
    // {{EXIT_CONDITIONS}}
    // This section will be populated based on user's exit rules
    
    // Example: Close on opposite RSI signal
    double rsi = iRSI(_Symbol, PERIOD_CURRENT, RSI_Period, PRICE_CLOSE);
    
    for (int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if (PositionSelectByTicket(ticket))
        {
            if (PositionGetInteger(POSITION_MAGIC) != MagicNumber)
                continue;
                
            ENUM_POSITION_TYPE posType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
            
            // Close buy if RSI overbought
            if (posType == POSITION_TYPE_BUY && rsi > RSI_Overbought)
            {
                ClosePosition(ticket);
            }
            
            // Close sell if RSI oversold
            if (posType == POSITION_TYPE_SELL && rsi < RSI_Oversold)
            {
                ClosePosition(ticket);
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Open Buy Order                                                   |
//+------------------------------------------------------------------+
void OpenBuyOrder()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double sl = price - StopLossPips * _Point * 10;
    double tp = price + TakeProfitPips * _Point * 10;
    
    double lotSize = CalculateLotSize(StopLossPips);
    
    MqlTradeRequest request = {};
    MqlTradeResult result = {};
    
    request.action = TRADE_ACTION_DEAL;
    request.symbol = _Symbol;
    request.volume = lotSize;
    request.type = ORDER_TYPE_BUY;
    request.price = price;
    request.sl = sl;
    request.tp = tp;
    request.deviation = 10;
    request.magic = MagicNumber;
    request.comment = "Prop Strategy Buy";
    
    if (OrderSend(request, result))
    {
        Print("Buy order opened: ", result.order, " at ", price);
    }
    else
    {
        Print("Buy order failed: ", GetLastError());
    }
}

//+------------------------------------------------------------------+
//| Open Sell Order                                                  |
//+------------------------------------------------------------------+
void OpenSellOrder()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = price + StopLossPips * _Point * 10;
    double tp = price - TakeProfitPips * _Point * 10;
    
    double lotSize = CalculateLotSize(StopLossPips);
    
    MqlTradeRequest request = {};
    MqlTradeResult result = {};
    
    request.action = TRADE_ACTION_DEAL;
    request.symbol = _Symbol;
    request.volume = lotSize;
    request.type = ORDER_TYPE_SELL;
    request.price = price;
    request.sl = sl;
    request.tp = tp;
    request.deviation = 10;
    request.magic = MagicNumber;
    request.comment = "Prop Strategy Sell";
    
    if (OrderSend(request, result))
    {
        Print("Sell order opened: ", result.order, " at ", price);
    }
    else
    {
        Print("Sell order failed: ", GetLastError());
    }
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                      |
//+------------------------------------------------------------------+
double CalculateLotSize(int stopLossPips)
{
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * (RiskPercent / 100.0);
    
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
    
    double stopLossAmount = stopLossPips * point / tickSize * tickValue;
    double lotSize = riskAmount / stopLossAmount;
    
    // Round to allowed lot step
    double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
    lotSize = MathFloor(lotSize / lotStep) * lotStep;
    
    // Check min/max lot
    double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
    double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
    
    lotSize = MathMax(minLot, MathMin(maxLot, lotSize));
    
    return lotSize;
}

//+------------------------------------------------------------------+
//| Check drawdown limits (CRITICAL for prop firms)                 |
//+------------------------------------------------------------------+
bool CheckDrawdownLimits()
{
    double currentBalance = AccountInfoDouble(ACCOUNT_BALANCE);
    double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);
    
    // Calculate daily drawdown
    double dailyDD = ((g_dailyStartBalance - currentEquity) / g_dailyStartBalance) * 100.0;
    
    // Calculate total drawdown
    double totalDD = ((g_initialBalance - currentEquity) / g_initialBalance) * 100.0;
    
    if (dailyDD >= MaxDailyDrawdown)
    {
        Print("ALERT: Daily drawdown limit reached! ", dailyDD, "% / ", MaxDailyDrawdown, "%");
        return false;
    }
    
    if (totalDD >= MaxTotalDrawdown)
    {
        Print("ALERT: Total drawdown limit reached! ", totalDD, "% / ", MaxTotalDrawdown, "%");
        return false;
    }
    
    return true;
}

//+------------------------------------------------------------------+
//| Reset daily balance at midnight                                  |
//+------------------------------------------------------------------+
void CheckDailyReset()
{
    datetime currentTime = TimeCurrent();
    MqlDateTime timeStruct;
    TimeToStruct(currentTime, timeStruct);
    
    if (timeStruct.hour == 0 && timeStruct.min == 0)
    {
        if (TimeCurrent() - g_lastDayCheck > 3600) // Avoid multiple resets
        {
            g_dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
            g_lastDayCheck = currentTime;
            Print("Daily balance reset: ", g_dailyStartBalance);
        }
    }
}

//+------------------------------------------------------------------+
//| Check if within trading hours                                    |
//+------------------------------------------------------------------+
bool IsWithinTradingHours()
{
    MqlDateTime timeStruct;
    TimeToStruct(TimeCurrent(), timeStruct);
    
    if (StartHour <= EndHour)
    {
        return (timeStruct.hour >= StartHour && timeStruct.hour < EndHour);
    }
    else // Overnight session
    {
        return (timeStruct.hour >= StartHour || timeStruct.hour < EndHour);
    }
}

//+------------------------------------------------------------------+
//| Count open positions with our magic number                       |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
    int count = 0;
    for (int i = 0; i < PositionsTotal(); i++)
    {
        ulong ticket = PositionGetTicket(i);
        if (PositionSelectByTicket(ticket))
        {
            if (PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            {
                count++;
            }
        }
    }
    return count;
}

//+------------------------------------------------------------------+
//| Close a specific position                                        |
//+------------------------------------------------------------------+
void ClosePosition(ulong ticket)
{
    MqlTradeRequest request = {};
    MqlTradeResult result = {};
    
    if (PositionSelectByTicket(ticket))
    {
        request.action = TRADE_ACTION_DEAL;
        request.position = ticket;
        request.symbol = PositionGetString(POSITION_SYMBOL);
        request.volume = PositionGetDouble(POSITION_VOLUME);
        request.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;
        request.price = (request.type == ORDER_TYPE_SELL) ? SymbolInfoDouble(request.symbol, SYMBOL_BID) : SymbolInfoDouble(request.symbol, SYMBOL_ASK);
        request.deviation = 10;
        request.magic = MagicNumber;
        
        if (OrderSend(request, result))
        {
            Print("Position closed: ", ticket);
        }
    }
}

//+------------------------------------------------------------------+
//| Close all positions                                              |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
    for (int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if (PositionSelectByTicket(ticket))
        {
            if (PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            {
                ClosePosition(ticket);
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Update trailing stops                                            |
//+------------------------------------------------------------------+
void UpdateTrailingStops()
{
    for (int i = 0; i < PositionsTotal(); i++)
    {
        ulong ticket = PositionGetTicket(i);
        if (PositionSelectByTicket(ticket))
        {
            if (PositionGetInteger(POSITION_MAGIC) != MagicNumber)
                continue;
                
            double currentSL = PositionGetDouble(POSITION_SL);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            ENUM_POSITION_TYPE posType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
            
            double trailDistance = TrailingStopPips * _Point * 10;
            
            if (posType == POSITION_TYPE_BUY)
            {
                double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
                double newSL = currentPrice - trailDistance;
                
                if (newSL > currentSL && newSL > openPrice)
                {
                    ModifyPosition(ticket, newSL, PositionGetDouble(POSITION_TP));
                }
            }
            else if (posType == POSITION_TYPE_SELL)
            {
                double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
                double newSL = currentPrice + trailDistance;
                
                if (newSL < currentSL && newSL < openPrice)
                {
                    ModifyPosition(ticket, newSL, PositionGetDouble(POSITION_TP));
                }
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Modify position SL/TP                                            |
//+------------------------------------------------------------------+
void ModifyPosition(ulong ticket, double sl, double tp)
{
    MqlTradeRequest request = {};
    MqlTradeResult result = {};
    
    request.action = TRADE_ACTION_SLTP;
    request.position = ticket;
    request.sl = sl;
    request.tp = tp;
    
    if (OrderSend(request, result))
    {
        Print("Position modified: ", ticket, " new SL: ", sl);
    }
}

//+------------------------------------------------------------------+
//| Update chart comment                                             |
//+------------------------------------------------------------------+
void UpdateComment()
{
    double currentBalance = AccountInfoDouble(ACCOUNT_BALANCE);
    double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);
    double dailyDD = ((g_dailyStartBalance - currentEquity) / g_dailyStartBalance) * 100.0;
    double totalDD = ((g_initialBalance - currentEquity) / g_initialBalance) * 100.0;
    
    string comment = "\n";
    comment += "===== PROP STRATEGY EA =====\n";
    comment += "Open Trades: " + IntegerToString(g_openTrades) + " / " + IntegerToString(MaxOpenTrades) + "\n";
    comment += "Balance: $" + DoubleToString(currentBalance, 2) + "\n";
    comment += "Equity: $" + DoubleToString(currentEquity, 2) + "\n";
    comment += "Daily DD: " + DoubleToString(dailyDD, 2) + "% / " + DoubleToString(MaxDailyDrawdown, 2) + "%\n";
    comment += "Total DD: " + DoubleToString(totalDD, 2) + "% / " + DoubleToString(MaxTotalDrawdown, 2) + "%\n";
    comment += "============================\n";
    
    Comment(comment);
}
//+------------------------------------------------------------------+
